version: "3.8"

services:
  app:
    build:
      context: ../app   # Adjust the context path as per your project structure
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ../app:/app
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
